name: Lint

on:
  push:
    paths:
      - ".github/workflows/lint.yaml"
      - "smartfeed/**"
      - "pyproject.toml"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          # - "3.8"
          # - "3.9"
          - "3.10"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.5
          virtualenvs-create: false
          installer-parallel: true

      - name: Install dependencies
        run: |
          poetry install --all-extras

      - name: Lint with mypy
        run: |
          poetry run mypy smartfeed

      - name: Lint with black
        run: |
          poetry run black --check smartfeed
