name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          # - "3.8"
          # - "3.9"
          - "3.10"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup poetry
        run: pip install poetry==1.4.1

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: /home/runner/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}

      - name: Install dependencies
        run: poetry install --all-extras

      - name: Make Test
        run: poetry run make test
      
      - name: Make Test Cache
        run: |
          docker-compose up sfredis -d
          poetry run make test_cache
