name: Test

on:
  push:
    paths:
      - ".github/workflows/tests.yaml"
      - "smartfeed/**"
      - "pyproject.toml"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          # - "3.8"
          - "3.9"
          - "3.10"
          - "3.12"
          - "3.13"

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.5
          virtualenvs-create: false
          installer-parallel: true

      - name: Install dependencies
        run: poetry install --all-extras

      - name: Make Test
        run: poetry run pytest
